version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}  # 파이썬 버전 지정
      ports:
        - "8000:8000"   # 호스트 8000 포트, 컨테이너 8000 포트
      env_file:
        - .env  # 환경변수 파일
      volumes:
        - ./app:/app    # 소스코드 로컬 ./app, 컨테이너 /app/app
        - ./data:/app/data  # 데이터 로컬 ./data, 컨테이너 /app/data
      network: 
        - app-network # 네트워크 설정

networks:
  app-network: