# wien0128 CI

name: wien0128 CI

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-Latest
    outputs:
      python_version: ${{ steps.get_python_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      # 파이썬 버전 가져오기
      - name: Get Python Version
        id: get_python_version
        run: |
          python_version=$(python scripts/get_python_version.py | jq -r .full)
          echo "version=${python_version}" >> $GITHUB_OUTPUT
      
      # requirements.txt 생성
      - name: Generate Requirements
        run: python scripts/generate_requirements.py

      # requirements.txt 캐싱
      - name: Cache Requirements
        uses: actions/cache@v3
        with:
          path: requirements.txt
          key: ${{ runner.os }}-requirements-${{ hashFiles('**/requirements.txt') }}